### ISSUE TITLE
Test with other registries

### ISSUE THREAD

**Issue by lstocchi** [redhat-actions/push-to-registry#3]
The action has already been tested by pushing docker/oci images to a Quay registry.

This needs to be tested with
- [x] other registries such as DockerHub
- [x] internal OpenShift registry

**Comment by lstocchi** [comment]
Tried with both and it works fine. Maybe i just need to add an input to set the tls-verify to false for openshift registry as in crc i get this error "x509: certificate signed by unknown authority"

For an internal OpenShift registry the values needed are:
```
- name: Push To Quay
      uses: redhat-actions/push-to-registry@v1
      with:
        image: ${{ env.IMAGE_NAME }}
        registry: ${{ secrets.OPENSHIFT_REGISTRY }} // something like  default-route-openshift-image-registry.apps-crc.testing/projectname
        username: ${{ secrets.OPENSHIFT_USERNAME }} // classic username used to login in openshift
        password: ${{ secrets.OPENSHIFT_TOKEN }} // the openshift token (not working by using the password)
```

What we need to mention is that the user need to have some specific roles to push/pull to the registry https://docs.openshift.com/container-platform/3.9/install_config/registry/accessing_registry.html#access-user-prerequisites

For dockerhub, the same as quay.io
```
- name: Push To Quay
      uses: redhat-actions/push-to-registry@v1
      with:
        image: ${{ env.IMAGE_NAME }}
        registry: ${{ secrets.DOCKER_REPO }} //docker.io/username
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_TOKEN }}
```
