### ISSUE TITLE
Output URL of pushed image

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/push-to-registry#4]
Currently I have to do the following to know where my image ended up:

`${{ env.IMAGE_REGISTRY }}/${{ env.QUAY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"`

This should be an output from this action.

**Comment by Divyansh42** [comment]
We are also taking these inputs in the action itself, can't we just use them directly, is it necessary to take all these from output of the action itself? Maybe that's the good practice (which I don't know) to proceed from the way you suggested. Please Let me know your thoughts on this.

**Comment by tetchel** [comment]
If you add it as an output, you can easily share it to another job, instead of having to re-emit the output yourself.

Currently I want to share the image URL into a second job (which deploys the image to openshift). So, I have to do:

```
    outputs:
      image_url: ${{ steps.resolve_image_url.outputs.image_url }}
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
<...>
      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.IMAGE_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.QUAY_USER }}
          username: ${{ env.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Resolve image URL
        id: resolve_image_url
        run: |
          echo "::set-output name=image_url::${{ env.IMAGE_REGISTRY }}/${{ env.QUAY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
```

If the push-to-registry action output the URL, I would not have to add the `resolve_image_url` step.
